version: '3.5'

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_server
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci