version: '3.5'
services:
  elasticsearch_v2:
    build: .
    container_name: elasticsearch_v2
    image: elasticsearch:v2
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - elastic_net

volumes:
  elastic:
    driver: local

networks:
  parlai_net:
    name: parlai_net
    driver: bridge

  elastic_net:
    name: elastic_net
    driver: bridge
